/**
 * Instagram DM Webhook Handler
 */

const bodyParser = require('body-parser');
const express = require('express');
const app = express();

app.use(bodyParser.json());

// Ignore favicon requests
app.get('/favicon.ico', (req, res) => res.status(204).end());
app.get('/favicon.png', (req, res) => res.status(204).end());

// Privacy Policy
app.get('/privacy', (req, res) => {
  res.send(`
    <html>
    <head><title>Privacy Policy - NYC Scout</title></head>
    <body style="font-family: sans-serif; padding: 40px; max-width: 800px; margin: 0 auto;">
      <h1>Privacy Policy</h1>
      
      <h2>About NYC Scout</h2>
      <p>NYC Scout is an automated chatbot that helps you discover events happening in New York City through Instagram direct messages.</p>
      
      <h2>Information We Collect</h2>
      <p>When you message NYC Scout on Instagram, we receive:</p>
      <ul>
        <li>Your Instagram user ID</li>
        <li>The content of messages you send to us</li>
        <li>Timestamp of your messages</li>
      </ul>
      
      <h2>How We Use Information</h2>
      <p>We use your messages to:</p>
      <ul>
        <li>Understand your event preferences and questions</li>
        <li>Generate relevant NYC event recommendations using AI</li>
        <li>Send automated responses with event information</li>
      </ul>
      
      <h2>AI-Powered Responses</h2>
      <p>NYC Scout uses artificial intelligence to process your questions and provide event recommendations. Your messages may be processed by AI systems to generate helpful responses.</p>
      
      <h2>Data Retention</h2>
      <p>Message data is processed in real-time and stored temporarily for service functionality. We do not sell or share your data with third parties for marketing purposes.</p>
      
      <h2>Contact</h2>
      <p>For questions about this policy, message us on Instagram @nyc_scout2026.</p>
    </body>
    </html>
  `);
});

// Terms of Service
app.get('/terms', (req, res) => {
  res.send(`
    <html>
    <head><title>Terms of Service - NYC Scout</title></head>
    <body style="font-family: sans-serif; padding: 40px; max-width: 800px; margin: 0 auto;">
      <h1>Terms of Service</h1>
      
      <h2>Acceptance of Terms</h2>
      <p>By messaging NYC Scout on Instagram, you agree to these terms.</p>
      
      <h2>Service Description</h2>
      <p>NYC Scout is an AI-powered chatbot that provides information about events in New York City. You can ask questions via Instagram DM and receive automated responses with event recommendations.</p>
      
      <h2>Automated Responses</h2>
      <p>All responses from NYC Scout are generated by artificial intelligence. While we strive for accuracy, event details may change. Always verify event information with official sources before attending.</p>
      
      <h2>User Responsibilities</h2>
      <p>You agree to:</p>
      <ul>
        <li>Use the service for legitimate event discovery purposes</li>
        <li>Not send spam, harmful, or abusive content</li>
        <li>Not attempt to manipulate or abuse the AI system</li>
      </ul>
      
      <h2>Limitation of Liability</h2>
      <p>NYC Scout is provided "as is" without warranties. We are not responsible for inaccurate event information or any decisions made based on our recommendations.</p>
      
      <h2>Changes to Terms</h2>
      <p>We may update these terms at any time. Continued use constitutes acceptance.</p>
      
      <h2>Contact</h2>
      <p>For questions, message us on Instagram @nyc_scout2026.</p>
    </body>
    </html>
  `);
});

const token = process.env.TOKEN || 'token';
const received_updates = [];

app.get('/', function(req, res) {
  res.send(`
    <html>
    <head><title>Instagram DMs</title></head>
    <body style="font-family: sans-serif; padding: 20px;">
      <h1>Instagram DMs</h1>
      <p>Received ${received_updates.length} messages</p>
      <pre style="background: #f4f4f4; padding: 15px; border-radius: 5px;">${JSON.stringify(received_updates, null, 2)}</pre>
    </body>
    </html>
  `);
});

app.get('/instagram', function(req, res) {
  if (
    req.query['hub.mode'] == 'subscribe' &&
    req.query['hub.verify_token'] == token
  ) {
    res.send(req.query['hub.challenge']);
  } else {
    res.sendStatus(400);
  }
});

app.post('/instagram', function(req, res) {
  console.log('Instagram webhook received:');
  console.log(JSON.stringify(req.body, null, 2));
  
  // Store raw payload for debugging
  received_updates.unshift({
    raw: req.body,
    received_at: new Date().toISOString()
  });
  
  if (req.body.entry) {
    req.body.entry.forEach(entry => {
      // Instagram uses "messaging" for DMs
      const messages = entry.messaging || entry.changes || [];
      
      messages.forEach(event => {
        // Handle standard messaging format
        if (event.message) {
          const dm = {
            type: 'message',
            sender_id: event.sender?.id,
            recipient_id: event.recipient?.id,
            timestamp: event.timestamp,
            message_text: event.message.text || null,
            message_id: event.message.mid,
            received_at: new Date().toISOString()
          };
          console.log('New Instagram DM:', dm);
          received_updates.unshift(dm);
        }
        
        // Handle "changes" format (used by some Instagram webhooks)
        if (event.field && event.value) {
          console.log('Instagram change event:', event.field, event.value);
          received_updates.unshift({
            type: 'change',
            field: event.field,
            value: event.value,
            received_at: new Date().toISOString()
          });
        }
      });
    });
  }
  
  res.sendStatus(200);
});

module.exports = app;
